trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  EnableCodeSigning: 'false'   # set to 'true' when ready
  ArtifactNameVar: $[coalesce(
                      replace(eq(variables['EnableCodeSigning'], 'true'), 'True', 'signed'),
                      'drop')]

stages:
# -----------------------
# Stage 1: Build
# -----------------------
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        addToPath: true

    - script: |
        echo "Installing conda environment"
        conda env create -f environment.yml -n Analytics
      displayName: 'Create Conda Environment'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Prepare Artifact Staging'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(ArtifactNameVar)'
      displayName: 'Publish Artifact'

# -----------------------
# Stage 2: Code Signing (optional)
# -----------------------
- stage: Sign
  condition: eq(variables['EnableCodeSigning'], 'true')
  dependsOn: Build
  jobs:
  - job: Sign
    steps:
    - download: current
      artifact: signed

    - powershell: |
        Write-Host "Code signing step would run here"
      displayName: 'Code Signing'

# -----------------------
# Stage 3: Deploy to Pilot
# -----------------------
- stage: Pilot
  dependsOn: [Build, Sign]
  jobs:
  - deployment: PilotDeploy
    environment: Pilot-Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(ArtifactNameVar)'

          - powershell: |
              Write-Host "Deploying Analytics Workstation to Pilot environment"
            displayName: 'Deploy to Pilot'

# -----------------------
# Stage 4: Release to Prod
# -----------------------
- stage: Prod
  dependsOn: Pilot
  jobs:
  - deployment: ProdDeploy
    environment: Prod-Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(ArtifactNameVar)'

          - powershell: |
              Write-Host "Deploying Analytics Workstation to Production environment"
            displayName: 'Deploy to Prod'
