trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  EnableCodeSigning: 'false'   # set to 'true' when ready
  ArtifactNameVar: $[coalesce(
                      replace(eq(variables['EnableCodeSigning'], 'true'), 'True', 'signed'),
                      'drop')]

stages:
# -----------------------
# Stage 1: Build
# -----------------------
- stage: Build
  displayName: "Build & Package"
  jobs:
  - job: Build
    steps:
    # Optional lint
    - powershell: |
        Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
        Invoke-ScriptAnalyzer -Path setup, scripts -Recurse -EnableExit
      displayName: "Lint scripts (PSScriptAnalyzer)"

    # Package repo into zip
    - powershell: |
        $zipPath = "$(Build.ArtifactStagingDirectory)\analytics-workstation.zip"
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
        [System.IO.Compression.ZipFile]::CreateFromDirectory("$(Build.SourcesDirectory)", $zipPath)
      displayName: "Package repository to ZIP"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
      displayName: "Publish artifact"


# -----------------------
# Stage 2: Code Signing (optional)
# -----------------------
- stage: Sign
  condition: eq(variables['EnableCodeSigning'], 'true')
  dependsOn: Build
  jobs:
  - job: Sign
    steps:
    - download: current
      artifact: signed

    - powershell: |
        Write-Host "Code signing step would run here"
      displayName: 'Code Signing'

# -----------------------
# Stage 3: Deploy to Pilot
# -----------------------
- stage: Pilot
  dependsOn: [Build, Sign]
  jobs:
  - deployment: PilotDeploy
    environment: Pilot-Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(ArtifactNameVar)'

          - powershell: |
              Write-Host "Deploying Analytics Workstation to Pilot environment"
            displayName: 'Deploy to Pilot'

# -----------------------
# Stage 4: Release to Prod
# -----------------------
- stage: Prod
  dependsOn: Pilot
  jobs:
  - deployment: ProdDeploy
    environment: Prod-Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(ArtifactNameVar)'

          - powershell: |
              Write-Host "Deploying Analytics Workstation to Production environment"
            displayName: 'Deploy to Prod'
